export interface DefaultItem {
  name: string;
  category: string;
  price?: number;
}

export const INDIAN_DEFAULT_ITEMS: DefaultItem[] = [
  // Others
  { name: 'Matchbox (Pack)', category: 'Others' },
  { name: 'Incense Sticks (Agarbatti)', category: 'Others' },
  { name: 'Aluminum Foil', category: 'Others' },
  { name: 'Garbage Bags', category: 'Others' },
  { name: 'Kitchen Tissues', category: 'Others' },
  { name: 'Candles (Pack)', category: 'Others' },
  { name: 'Batteries (AA/AAA)', category: 'Others' },
  
  // Dairy & Bakery
  { name: 'Milk (1L)', category: 'Dairy' },
  { name: 'Paneer (200g)', category: 'Dairy' },
  { name: 'Curd (500g)', category: 'Dairy' },
  { name: 'Butter (100g)', category: 'Dairy' },
  { name: 'Eggs (6pcs)', category: 'Dairy' },
  { name: 'Brown Bread', category: 'Bakery' },
  { name: 'Pav (Pack of 6)', category: 'Bakery' },
  { name: 'Rusks (Toast)', category: 'Bakery' },
  { name: 'Cheese Slices', category: 'Dairy' },
  { name: 'Fresh Cream (250ml)', category: 'Dairy' },
  { name: 'Greek Yogurt', category: 'Dairy' },
  { name: 'Condensed Milk', category: 'Dairy' },
  
  // Vegetables
  { name: 'Onions (1kg)', category: 'Vegetables' },
  { name: 'Potatoes (1kg)', category: 'Vegetables' },
  { name: 'Tomatoes (1kg)', category: 'Vegetables' },
  { name: 'Green Chillies (100g)', category: 'Vegetables' },
  { name: 'Ginger (100g)', category: 'Vegetables' },
  { name: 'Garlic (100g)', category: 'Vegetables' },
  { name: 'Coriander (Bunch)', category: 'Vegetables' },
  { name: 'Spinach (Palak)', category: 'Vegetables' },
  { name: 'Ladies Finger (Bhindi)', category: 'Vegetables' },
  { name: 'Carrots (500g)', category: 'Vegetables' },
  { name: 'Capsicum (250g)', category: 'Vegetables' },
  { name: 'Cauliflower', category: 'Vegetables' },
  { name: 'Green Peas (500g)', category: 'Vegetables' },
  { name: 'Cabbage', category: 'Vegetables' },
  { name: 'Lemons (4pcs)', category: 'Vegetables' },
  { name: 'Broccoli', category: 'Vegetables' },
  { name: 'Mushrooms (200g)', category: 'Vegetables' },
  { name: 'Spring Onions', category: 'Vegetables' },
  { name: 'Sweet Corn (250g)', category: 'Vegetables' },
  { name: 'Cucumber', category: 'Vegetables' },
  
  // Fruits
  { name: 'Bananas (Dozen)', category: 'Fruits' },
  { name: 'Apples (1kg)', category: 'Fruits' },
  { name: 'Mangoes (1kg)', category: 'Fruits' },
  { name: 'Oranges (1kg)', category: 'Fruits' },
  { name: 'Papaya', category: 'Fruits' },
  { name: 'Grapes (500g)', category: 'Fruits' },
  { name: 'Watermelon', category: 'Fruits' },
  { name: 'Pomegranate (1kg)', category: 'Fruits' },
  { name: 'Pineapple', category: 'Fruits' },
  { name: 'Guava (1kg)', category: 'Fruits' },
  { name: 'Pear (500g)', category: 'Fruits' },
  { name: 'Kiwi (3pcs)', category: 'Fruits' },
  
  // Staples & Groceries
  { name: 'Atta (5kg)', category: 'Staples' },
  { name: 'Rice (Basmati 1kg)', category: 'Staples' },
  { name: 'Poha (500g)', category: 'Staples' },
  { name: 'Rava/Sooji (500g)', category: 'Staples' },
  { name: 'Dal Tadka (500g)', category: 'Staples' },
  { name: 'Moong Dal (500g)', category: 'Staples' },
  { name: 'Chana Dal (500g)', category: 'Staples' },
  { name: 'Toor Dal (1kg)', category: 'Staples' },
  { name: 'Urad Dal (500g)', category: 'Staples' },
  { name: 'Kabuli Chana', category: 'Staples' },
  { name: 'Black Chana', category: 'Staples' },
  { name: 'Rajma (Kidney Beans)', category: 'Staples' },
  { name: 'Sugar (1kg)', category: 'Staples' },
  { name: 'Salt (1kg)', category: 'Staples' },
  { name: 'Jaggery (Gur)', category: 'Staples' },
  { name: 'Sunflower Oil (1L)', category: 'Staples' },
  { name: 'Mustard Oil (1L)', category: 'Staples' },
  { name: 'Ghee (500ml)', category: 'Staples' },
  { name: 'Tea Powder (250g)', category: 'Staples' },
  { name: 'Coffee (100g)', category: 'Staples' },
  { name: 'Honey (250g)', category: 'Staples' },
  { name: 'Maida (All Purpose Flour)', category: 'Staples' },
  { name: 'Besan (Gram Flour)', category: 'Staples' },
  
  // Spices & Masalas
  { name: 'Turmeric Powder', category: 'Spices' },
  { name: 'Red Chilli Powder', category: 'Spices' },
  { name: 'Coriander Powder', category: 'Spices' },
  { name: 'Garam Masala', category: 'Spices' },
  { name: 'Cumin Seeds (Jeera)', category: 'Spices' },
  { name: 'Mustard Seeds (Rai)', category: 'Spices' },
  { name: 'Cardamom (Elaichi)', category: 'Spices' },
  { name: 'Cloves (Laung)', category: 'Spices' },
  { name: 'Black Pepper', category: 'Spices' },
  { name: 'Biryani Masala', category: 'Spices' },
  { name: 'Sambar Powder', category: 'Spices' },
  { name: 'Hing (Asafoetida)', category: 'Spices' },
  { name: 'Cinnamon Sticks', category: 'Spices' },
  { name: 'Bay Leaves', category: 'Spices' },
  
  // Snacks & Others
  { name: 'Maggi (Pack of 4)', category: 'Snacks' },
  { name: 'Pasta (500g)', category: 'Snacks' },
  { name: 'Biscuits (Marie Gold)', category: 'Snacks' },
  { name: 'Good Day Biscuits', category: 'Snacks' },
  { name: 'Namkeen (Bhujia)', category: 'Snacks' },
  { name: 'Potato Chips', category: 'Snacks' },
  { name: 'Tomato Ketchup', category: 'Snacks' },
  { name: 'Mixed Jam', category: 'Snacks' },
  { name: 'Peanut Butter', category: 'Snacks' },
  { name: 'Mayonnaise', category: 'Snacks' },
  { name: 'Corn Flakes', category: 'Snacks' },
  { name: 'Muesli', category: 'Snacks' },
  { name: 'Roasted Almonds', category: 'Snacks' },
  { name: 'Cashews (200g)', category: 'Snacks' },
  
  // Household
  { name: 'Dishwash Bar/Liquid', category: 'Household' },
  { name: 'Detergent Powder', category: 'Household' },
  { name: 'Detergent Soap', category: 'Household' },
  { name: 'Fabric Softener', category: 'Household' },
  { name: 'Toilet Cleaner', category: 'Household' },
  { name: 'Floor Cleaner', category: 'Household' },
  { name: 'Hand Wash Refill', category: 'Household' },
  
  // Personal Care
  { name: 'Toothpaste', category: 'Personal Care' },
  { name: 'Toothbrush', category: 'Personal Care' },
  { name: 'Bathing Soap', category: 'Personal Care' },
  { name: 'Shampoo', category: 'Personal Care' },
  { name: 'Conditioner', category: 'Personal Care' },
  { name: 'Face Wash', category: 'Personal Care' },
  { name: 'Moisturizer', category: 'Personal Care' },
  { name: 'Deodorant', category: 'Personal Care' },
  { name: 'Sanitary Pads', category: 'Personal Care' },
  { name: 'Hand Sanitizer', category: 'Personal Care' },
  { name: 'Shaving Cream', category: 'Personal Care' },
  
  // Beverages
  { name: 'Fruit Juice (1L)', category: 'Beverages' },
  { name: 'Coconut Water', category: 'Beverages' },
  { name: 'Soft Drink (2L)', category: 'Beverages' },
  { name: 'Green Tea Bags', category: 'Beverages' },
  { name: 'Health Drink (Bournvita/Horlicks)', category: 'Beverages' },
  { name: 'Mineral Water (20L)', category: 'Beverages' }
];
